# Generated by Django 4.0.6 on 2022-07-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_p', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_p', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('question', models.TextField(max_length=300, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_p', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_p', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text_answer', models.TextField(max_length=500, verbose_name='Ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='webapp.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'choices',
            },
        ),
    ]
