# Generated by Django 4.0.6 on 2022-07-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_p', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_p', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('choice', models.ManyToManyField(related_name='answer_variants', to='webapp.choice', verbose_name='Варианты ответов')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='webapp.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'answers',
            },
        ),
    ]
